In [2]:
#Importation of functions/libraries to be used in the classification
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer #lexical database for English language that offer lemmatization
from sklearn.preprocessing import LabelEncoder #converting the labels into numeric form 
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer # Transforms text to feature vectors
from sklearn import model_selection, naive_bayes
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.linear_model.logistic import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score 
import matplotlib.pyplot as plt #For visualization
import xlrd
import openpyxl

In [3]:
import os
#my_path = r'C:\Users\216068813\Documents'
my_path = r'E:\Japheth Mursi docs\Python'
%time df = pd.read_excel(os.path.join(my_path,'PD1_5.xlsx'))

Wall time: 36.2 s


In [2]:
#%pip install sklearn_pandas
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()

Saving PD1_5.xlsx to PD1_5.xlsx


## 1: Load  dataset 

In [3]:
import io

df= pd.read_excel(io.BytesIO(uploaded['PD1_5.xlsx']))

In [4]:
#Get the shape of the dataset
df.shape

(49193, 36)

In [4]:
#chunk.clean_text=chunk.clean_text.astype(str)
df.pt1=df.pt1.astype(str)
df.pt2=df.pt2.astype(str)
df.pt3=df.pt3.astype(str)
df.pt4=df.pt4.astype(str)
df.pt5=df.pt5.astype(str)

## 2: Import ML libraries

In [5]:
from sklearn.model_selection import train_test_split
from sklearn_pandas import DataFrameMapper
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
df= df.dropna()

## 3: Declare predictors and target variable
The prediction Model is developed using a three feature vectors/ attributes:
* <T:Clean_text>: Preprocessed tweet
* <W:Weightage>: Presence or absence of narcissistic related word/Clean text based on the narcissistic dictionary
* <S: Statuses Count>: Number of tweets (statuses posted) made by the user. We classify tweets made by users into three categories for the purspose to classifier training as follows; 
    * Users with tweets Less than 10,000;
	* Users with tweets above 10000 but less than 50,000;
	* Users with tweets More than 50,000 



In [6]:
#dk=df
df.head(2)

text  \
0  This is the worst year possible to be obsessed...   
1  Tony Blair extract worse than thought of paren...   

                                                 pt1  \
0  this is the worst year possible to be obsessed...   
1  tony blair extract worse than thought of paren...   

                                                 pt2  \
0  this is the worst year possible to be obsessed...   
1  tony blair extract worse than thought of paren...   

                                                 pt3  \
0  worst year possible obsessed someone want ever...   
1  tony blair extract worse thought parents sex i...   

                                              tokens  \
0  ['worst', 'year', 'possible', 'obsessed', 'som...   
1  ['tony', 'blair', 'extract', 'worse', 'thought...   

                                               stems  \
0  ['worst', 'year', 'possibl', 'obsess', 'someon...   
1  ['toni', 'blair', 'extract', 'wors', 'thought'...   

                                                 pt4  \
0  worst year possibl obsess someon want everi si...   
1  toni blair extract wors thought parent sex ira...   

                                              lemmas  \
0  worst year possible obsessed someone want ever...   
1  tony blair extract worse thought parents sex i...   

                                                 pt5       SS1  ...  Gn  Vn5  \
0  bad year possible obsess someone want every si... -0.467857  ...   0    0   
1  tony blair extract bad thought parent sex iraq... -0.466667  ...   0    0   

   Gn5  Vn1 Gn1  Vn2  Gn2 Vn3  Gn3 SPL5.1  
0    0    0   0    0    0   0    0    NaN  
1    0    0   0    0    0   0    0    NaN  

[2 rows x 36 columns]

In [ ]:
df.pt4=df.pt4.astype(str)

In [7]:
#Add the features of the dataframe that you want to transform and/or combine
mapper = DataFrameMapper([
     ('pt1', TfidfVectorizer(min_df=.0025, max_df=0.8, stop_words='english',ngram_range=(1,2))),#max_df=0.8, min_df=2),
     ])
    #('No_of_category',None),
     #('Vn5', None)])

## 4a:Split the dataset to training and test dataset and map features to target variable

In [8]:
#Map predictor Variables to Target Variable
features = mapper.fit_transform(df)
categories = df['SPL1']
 
# Split the data between train and test
#X_Train, X_Test, Y_Train, Y_Test = train_test_split(features, categories ,test_size=0.2,train_size=0.8)

In [9]:
# Split the data between train and test
X_Train, X_Test, Y_Train, Y_Test = train_test_split(features, categories ,test_size=0.2,train_size=0.8)

In [10]:
#Show the size of the split train and test dataset
X_Train.shape

(39354, 692)

## 4b:Training using selected ML Classifiers
Training refers to the process where we “teach” the classifier (e.g naïve bayes )
by using “fit” to the training data  (X_Train , Y_Train) to be able to 
learn data attributes and evaluate its accuracy based on the (20%) test data 

In [11]:
# fit the training dataset on the NB classifier
Naive = naive_bayes.MultinomialNB()
Naive=MultinomialNB().fit(X_Train,Y_Train)
Naive.fit(X_Train,Y_Train) #Fit the model according to the given training data
# predict the labels on test dataset
NB_pred = Naive.predict(X_Test)
# Use accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(NB_pred, Y_Test)*100)

Naive Bayes Accuracy Score ->  83.44343937392011


In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

NB_pred_CM = confusion_matrix(Y_Test, NB_pred)
print(NB_pred_CM)
print('Accuracy' + str(accuracy_score(Y_Test, NB_pred)))

[[7462   13   27]
 [ 489   96   14]
 [1074   12  652]]
Accuracy0.8344343937392011


In [13]:
print(classification_report(Y_Test, NB_pred))
print()
print(accuracy_score(Y_Test, NB_pred))

              precision    recall  f1-score   support

           0       0.83      0.99      0.90      7502
           1       0.79      0.16      0.27       599
           2       0.94      0.38      0.54      1738

    accuracy                           0.83      9839
   macro avg       0.85      0.51      0.57      9839
weighted avg       0.84      0.83      0.80      9839


0.8344343937392011


###  RF 

In [ ]:
#Random forest accuracy with three predictor variables
from sklearn.ensemble import RandomForestClassifier
Rf2 = RandomForestClassifier(n_estimators=180,max_leaf_nodes=None, 
                                 n_jobs=-1)
Rf2.fit(X_Train,Y_Train)
Rf2_pred = Rf2.predict(X_Test)
print('Random forest accuracy %s' % accuracy_score(Rf2_pred , Y_Test))

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

RF_pred_CM2 = confusion_matrix(Y_Test, Rf2_pred)
print(RF_pred_CM2)
print('Accuracy' + str(accuracy_score(Y_Test, Rf2_pred)))

[[19365   466   255]
 [  514  4369    58]
 [  637   150  2673]]
Accuracy0.9269842384245446


In [ ]:
print(classification_report(Y_Test, Rf2_pred))
print()
print(accuracy_score(Y_Test, Rf2_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95     20086
           1       0.88      0.88      0.88      4941
           2       0.90      0.77      0.83      3460

    accuracy                           0.93     28487
   macro avg       0.91      0.87      0.89     28487
weighted avg       0.93      0.93      0.93     28487


0.9269842384245446


In [ ]:
#from sklearn.linear_model.logistic import LogisticRegression
from sklearn.linear_model import LogisticRegression

### Logistic regression classifier training,evaluation and confusion matrix

In [ ]:
# fit the training dataset on the logistic rregression and predict test dataset
Logistic = LogisticRegression()
Logistic.fit(X_Train,Y_Train)
Lg_pred1 = Logistic.predict(X_Test)
# Use accuracy_score function to get the accuracy
print("Logistic regression Accuracy Score -> ",accuracy_score(Lg_pred1, Y_Test)*100)

Logistic regression Accuracy Score ->  90.80191076328894


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
